/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.weddinggiftlisting.ui;
import com.mycompany.weddinggiftlisting.AlternateRowColorRenderer;
import com.mycompany.weddinggiftlisting.PositiveIntegerFilter;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author lokeshmakode
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initUI();
        initializeDB();
        loadTableData();
    }
    private void applyAlternateRowColors() {
        for (int i = 0; i < dataTable.getColumnCount(); i++) {
            dataTable.getColumnModel().getColumn(i).setCellRenderer(new AlternateRowColorRenderer());
        }
    }
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        model.setRowCount(0); // Clear existing rows

        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:data.db"); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT id, name, number, village, mode, amount FROM entries ORDER BY id DESC")) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getString("number"),
                    rs.getString("village"),
                    rs.getString("mode"),
                    rs.getInt("amount"),
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        applyAlternateRowColors();
    }

    private void setIntegerOnlyFilter(JTextField textField) {
        AbstractDocument doc = (AbstractDocument) textField.getDocument();
        doc.setDocumentFilter(new PositiveIntegerFilter());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        villageField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nameValueLable = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numberValueLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        amountValueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setAlignmentX(5.0F);
        jPanel1.setAlignmentY(5.0F);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("   Name");
        jLabel1.setIconTextGap(10);
        jPanel3.add(jLabel1);

        nameField.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        nameField.setText("jTextField1");
        jPanel3.add(nameField);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("   Number");
        jLabel2.setIconTextGap(10);
        jPanel3.add(jLabel2);

        numberField.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numberField.setText("jTextField2");
        jPanel3.add(numberField);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("   Village");
        jLabel3.setIconTextGap(10);
        jPanel3.add(jLabel3);

        villageField.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        villageField.setText("jTextField3");
        jPanel3.add(villageField);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("   Amount");
        jLabel4.setIconTextGap(10);
        jPanel3.add(jLabel4);

        amountField.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        amountField.setText("jTextField4");
        jPanel3.add(amountField);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("   Payment Mode");
        jPanel3.add(jLabel6);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Cash");
        jPanel3.add(jRadioButton1);
        jPanel3.add(jLabel7);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jRadioButton2.setText("Online ( UPI / Paytm / Google Pay / PhonePe )");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jPanel3.add(jLabel5);

        saveButton.setBackground(new java.awt.Color(0, 0, 0));
        saveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel3.add(saveButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Name      ");
        jPanel2.add(jLabel8);

        nameValueLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameValueLable.setText("jLabel9");
        jPanel2.add(nameValueLable);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Mobile No ");
        jPanel2.add(jLabel10);

        numberValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberValueLabel.setText("jLabel11");
        jPanel2.add(numberValueLabel);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Amount .  ");
        jPanel2.add(jLabel12);

        amountValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountValueLabel.setText("jLabel13");
        jPanel2.add(amountValueLabel);

        getContentPane().add(jPanel2);

        dataTable.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sr. Num.", "Name", "Mobile No.", "Village", "Payment mode", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dataTable.setEnabled(false);
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setPreferredWidth(1);
            dataTable.getColumnModel().getColumn(1).setPreferredWidth(3);
            dataTable.getColumnModel().getColumn(2).setPreferredWidth(3);
            dataTable.getColumnModel().getColumn(3).setPreferredWidth(2);
            dataTable.getColumnModel().getColumn(4).setPreferredWidth(1);
            dataTable.getColumnModel().getColumn(5).setPreferredWidth(1);
        }

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String name = nameField.getText();
        String number = numberField.getText();
        String village = villageField.getText();
        String amountText = amountField.getText();
        String mode = jRadioButton1.isSelected() ? "0" : "1";
        if (name.isEmpty() || number.isEmpty() || village.isEmpty() || amountText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            double amount = Double.parseDouble(amountText);
            try (Connection conn = DriverManager.getConnection("jdbc:sqlite:data.db");
                 PreparedStatement stmt = conn.prepareStatement("INSERT INTO entries (name, number, village, mode, amount) VALUES (?, ?, ?, ?, ?)");) {
                stmt.setString(1, name);
                stmt.setString(2, number);
                stmt.setString(3, village);
                stmt.setString(4, mode);
                stmt.setDouble(5, amount);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Entry saved successfully!");
                nameValueLable.setText(name);
                numberValueLabel.setText(number);
                amountValueLabel.setText(amount+"");
                loadTableData();
                clearUI();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid amount!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error!", "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountValueLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameValueLable;
    private javax.swing.JTextField numberField;
    private javax.swing.JLabel numberValueLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField villageField;
    // End of variables declaration//GEN-END:variables

    private void clearUI()
    {
        nameField.setText("");
        numberField.setText("");
        villageField.setText("");
        amountField.setText("");
        jRadioButton1.setSelected(true);

    }
    private void initUI() {
        clearUI();
        setIntegerOnlyFilter(numberField);
        setIntegerOnlyFilter(amountField);
             
    }

    private void initializeDB() {
        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:data.db");
                   Statement stmt = conn.createStatement()) {
                  String sql = "CREATE TABLE IF NOT EXISTS entries ("
                          + "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                          + "name TEXT,"
                          + "number TEXT,"
                          + "village TEXT,"
                          + "mode TEXT,"
                          + "amount INTEGER)";
                  stmt.execute(sql);
        } catch (SQLException e) {
        }
    }
    
}
